FROM openjdk:17.0.1-jdk-oracle

# direktori
WORKDIR /app

# Create the data directory where the H2 database file will be stored
RUN mkdir -p /app/data

# copy jar file
COPY target/*.jar app.jar

# expose
EXPOSE 9002

# run
CMD ["java", "-jar", "app.jar"]